included:
  - Common
  - Common_Tests
  - Sources
  - Tests
  - UIRounding_iOS
  - UIRounding_iOSTests
  - UIRounding_macOS
  - UIRounding_macOSTests
  - UIRounding_tvOS
  - UIRounding_tvOSTests
  - UIRounding_watchOS
excluded:
  - Pods
  - Carthage
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_optional_boolean
  - empty_count
  - explicit_init
  - extension_access_modifier
  - fatal_error_message
  - first_where
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_parameters
  - nimble_operator
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - switch_case_on_newline
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

cyclomatic_complexity: 10
file_length: 500
function_body_length: 50
function_parameter_count: 5
type_body_length: 300

type_name:
  min_length:
    error: 2
    warning: 3
  excluded:
    - Ad

identifier_name:
  min_length:
    error: 2
    warning: 3
  excluded:
    - id
    - ad
line_length: 140
number_separator:
  minimum_length: 5

custom_rules:
  open_bracket_blank_line:
    included: ".*\\.swift"
    name: "blank line after open bracket"
    regex: "\\{\n[[[:blank:]]\n]*\n"
    message: "Blank line after open bracket should be removed"
    severity: warning
  closed_brackets_blank_line:
    included: ".*\\.swift"
    name: "blank lines between closed brackets"
    regex: "\\}\n[[[:blank:]]\n]*\n\\}"
    message: "Blank lines between closed brackets should be removed"
    severity: warning
