language: swift
osx_image: xcode9.2
cache:
  directories:
  - Carthage
before_install:
- brew outdated carthage || brew upgrade carthage
- brew outdated swiftlint || brew upgrade swiftlint
before_script:
- rm -rf ~/Library/Developer/Xcode/DerivedData
- carthage bootstrap --no-use-binaries --cache-builds --platform $CARTHAGE_PLATFORM
script:
  - set -o pipefail
  - xcodebuild clean
  - xcodebuild build -project $PROJECT_NAME -scheme $SCHEME_NAME -destination "$DESTINATION" ENABLE_TESTABILITY=YES CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO | xcpretty
  - xcodebuild test -project $PROJECT_NAME -scheme $SCHEME_NAME -destination "$DESTINATION" ENABLE_TESTABILITY=YES CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO | xcpretty
env:
  global:
  - PROJECT_NAME: UIRounding.xcodeproj
  - secure: gLnUvgO0+/Uzj02g+R/TfX8gH2lqVPbz9LJ2fyJ/Hl6Chd3RvZI1Bs8dVumEzypuwOmWIlcBTbWm6jY87z5gl/WoS6wGyZyUOM5z0cMdIsu7rQDR678PofetSl1yAtqelM0KSQYWPOmCcSKz/EOp7j41BrfSANwszYDpX2WRfAUg7YskKPfs3Dt40diyUIMsbaxM+I0U3iF6VWVYlhHRHLt7zS1notdv4WYkE1fswaCez957w/UPKOoAaBOMKfODMV9WkC4VCphmY2//ZA4ETDu3ofi+znsQDnPIf8r/UjBy7gQgDQOZytwxpVJz8S5CrCspY8fMM9Mr05982VfGxr0YQSGadomnsapUz6YkywSsy1c3CBA+cDH4V9pYHd3j+SyHDL0i/Q4wxqq4jnWlmtfAzS9+6NTV4WnoI6wzi0wa6zkAgn2tQYYHxX1f3JTy1tRdZDARkpZZwz5vrAUTQxDMSb/nWJ5fzdddhYYklYNRSucAMSgA0pVkL003m803QUX3IDLWmgNI0jN7RPKA3MchppMP6KfubBJdB3jI/23emRaXYOAFplKBcF6AcAvazfw1HWqQsjBz6W3bt5cdAURWvCt7W5WuAvc3hv0YP07MjZkF130A6C7aHWzdUY3htQEGaqd6PlQaC9Wa4AIpKVfh2H9B653h7WS4rLdbUw0=
  matrix:
  - SCHEME_NAME="UIRounding_iOS" DESTINATION="platform=iOS Simulator,name=iPhone X,OS=11.2" CARTHAGE_PLATFORM="ios"
  - SCHEME_NAME="UIRounding_iOS" DESTINATION="platform=iOS Simulator,name=iPhone 7 Plus,OS=11.2" CARTHAGE_PLATFORM="ios"
  - SCHEME_NAME="UIRounding_iOS" DESTINATION="platform=iOS Simulator,name=iPhone 6,OS=10.3.1" CARTHAGE_PLATFORM="ios"
  - SCHEME_NAME="UIRounding_iOS" DESTINATION="platform=iOS Simulator,name=iPhone 5s,OS=9.3" CARTHAGE_PLATFORM="ios"
  - SCHEME_NAME="UIRounding_iOS" DESTINATION="platform=iOS Simulator,name=iPhone 4s,OS=8.3" CARTHAGE_PLATFORM="ios"

  - SCHEME_NAME="UIRounding_macOS" DESTINATION="arch=x86_64" CARTHAGE_PLATFORM="macos"
