language: swift
osx_image: xcode10
before_install:
- brew outdated swiftlint || brew upgrade swiftlint
- gem update cocoapods
- pod repo update
before_script:
- rm -rf ~/Library/Developer/Xcode/DerivedData
- if [ $COVERAGE == "YES" ]; then
    gem install slather;
    curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter;
    chmod +x ./cc-test-reporter;
    ./cc-test-reporter before-build;
  fi
script:
  - set -o pipefail
  - xcodebuild clean
  - xcodebuild build -workspace $PROJECT_NAME -scheme $SCHEME_NAME -destination "$DESTINATION" ENABLE_TESTABILITY=YES CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=YES | xcpretty
  - if [ $TESTING == "YES" ]; then
      xcodebuild test -worskpace $PROJECT_NAME -scheme $SCHEME_NAME -destination "$DESTINATION" ENABLE_TESTABILITY=YES CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=YES | xcpretty;
    fi
  - if [ $COVERAGE == "YES" ]; then
      slather coverage -x -t --scheme $SCHEME_NAME $PROJECT_NAME;
    fi
after_script:
  - if [ $COVERAGE == "YES" ]; then
      ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -t cobertura;
    fi
env:
  global:
  - PROJECT_NAME: UIRounding.xcworkspace
  - CC_TEST_REPORTER_ID: 40a67e2ea988f8785b6a3e6a95d9731f6acdec19e737a9d06771ae939e385359
  - secure: gLnUvgO0+/Uzj02g+R/TfX8gH2lqVPbz9LJ2fyJ/Hl6Chd3RvZI1Bs8dVumEzypuwOmWIlcBTbWm6jY87z5gl/WoS6wGyZyUOM5z0cMdIsu7rQDR678PofetSl1yAtqelM0KSQYWPOmCcSKz/EOp7j41BrfSANwszYDpX2WRfAUg7YskKPfs3Dt40diyUIMsbaxM+I0U3iF6VWVYlhHRHLt7zS1notdv4WYkE1fswaCez957w/UPKOoAaBOMKfODMV9WkC4VCphmY2//ZA4ETDu3ofi+znsQDnPIf8r/UjBy7gQgDQOZytwxpVJz8S5CrCspY8fMM9Mr05982VfGxr0YQSGadomnsapUz6YkywSsy1c3CBA+cDH4V9pYHd3j+SyHDL0i/Q4wxqq4jnWlmtfAzS9+6NTV4WnoI6wzi0wa6zkAgn2tQYYHxX1f3JTy1tRdZDARkpZZwz5vrAUTQxDMSb/nWJ5fzdddhYYklYNRSucAMSgA0pVkL003m803QUX3IDLWmgNI0jN7RPKA3MchppMP6KfubBJdB3jI/23emRaXYOAFplKBcF6AcAvazfw1HWqQsjBz6W3bt5cdAURWvCt7W5WuAvc3hv0YP07MjZkF130A6C7aHWzdUY3htQEGaqd6PlQaC9Wa4AIpKVfh2H9B653h7WS4rLdbUw0=
  matrix:
  - SCHEME_NAME="UIRounding_iOS" DESTINATION="name=iPhone X,OS=11.3" CARTHAGE_PLATFORM="ios" TESTING="YES" COVERAGE="NO"
  - SCHEME_NAME="UIRounding_iOS" DESTINATION="name=iPhone 7 Plus,OS=11.3" CARTHAGE_PLATFORM="ios" TESTING="YES" COVERAGE="NO"
  - SCHEME_NAME="UIRounding_iOS" DESTINATION="name=iPhone 6,OS=10.3.1" CARTHAGE_PLATFORM="ios" TESTING="YES" COVERAGE="NO"
  - SCHEME_NAME="UIRounding_iOS" DESTINATION="name=iPhone 5s,OS=9.3" CARTHAGE_PLATFORM="ios" TESTING="YES" COVERAGE="NO"

  - SCHEME_NAME="UIRounding_macOS" DESTINATION="arch=x86_64" CARTHAGE_PLATFORM="macos" TESTING="YES" COVERAGE="NO"

  - SCHEME_NAME="UIRounding_tvOS" DESTINATION="name=Apple TV 4K,OS=11.3" CARTHAGE_PLATFORM="tvos" TESTING="YES" COVERAGE="NO"
  - SCHEME_NAME="UIRounding_tvOS" DESTINATION="name=Apple TV 1080p,OS=10.2" CARTHAGE_PLATFORM="tvos" TESTING="YES" COVERAGE="NO"
  - SCHEME_NAME="UIRounding_tvOS" DESTINATION="name=Apple TV 1080p,OS=9.2" CARTHAGE_PLATFORM="tvos" TESTING="YES" COVERAGE="NO"

  - SCHEME_NAME="UIRounding_watchOS" DESTINATION="name=Apple Watch - 42mm,OS=4.3" CARTHAGE_PLATFORM="watchos" TESTING="NO" COVERAGE="NO"
  - SCHEME_NAME="UIRounding_watchOS" DESTINATION="name=Apple Watch - 42mm,OS=3.2" CARTHAGE_PLATFORM="watchos" TESTING="NO" COVERAGE="NO"
  - SCHEME_NAME="UIRounding_watchOS" DESTINATION="name=Apple Watch - 38mm,OS=2.2" CARTHAGE_PLATFORM="watchos" TESTING="NO" COVERAGE="NO"
