os: osx
language: swift
osx_image: xcode9.2
branches:
  only:
  - develop
  - master
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=UIRounding.xcodeproj
  - IOS_FRAMEWORK_SCHEME="UIRounding_iOS"
  - OSX_FRAMEWORK_SCHEME="UIRounding_macOS"
  - TVOS_FRAMEWORK_SCHEME="UIRounding_tvOS"
  - WATCHOS_FRAMEWORK_SCHEME="UIRounding_watchOS"
  - IOS_SDK=iphonesimulator11.2
  - OSX_SDK=macosx10.13
  - TVOS_SDK=appletvsimulator11.2
  - WATCHOS_SDK=watchsimulator4.2
  - secure: nEwSLlgxZxN06ODq/BLLNM0dmHaMsK6WjcQ5r6KsHhQAxkooJ2Ao8RZEHz7jWpTnKr7vmbHrLtFBIQtzK0wPVbr7Mbrk84JbzxkN1CjZfdDmTCxJLQ/rM9cAv7eA9/D0ZTxlu6Ze8Wi8wEiPNna3pxr6e3GxekwDA97GTFdsrhaKZEdXlxCzBiN81UqVeryVOslS2VCEf0VdPDrH1pQBHsuJYX3+G7XugFV0Z1V5A2sGpagqpUc2F659+hE4bgl1bk+Tt/jCfamZGYj+B+gC7HLsI7Np7jsUTvJXkDjhG8eYfXpVJ0s+t5LjC1nskqkb4bMFumzOO0xaUR2EUEzjww5Rbet2tQzHry3e0L2IIMiD3SNLnlRHNxS+5VlazHVxJFQeIIWi3IccwjZ219Jr9zN07B4bghlZW0w7oiZ9oDOF9HjZJYTm/YRVI/H+PZoGZ32N5SX4LfrSdmUSlWieOkYEI6v4VYRJF4dOQ8iBeqN/JHKO3G0efgRBu2YNR6jFdy8PSoD+0IoKCwdC803j1lsDriR8ETAP2bCxw0HK1nV1vmh9kNnHq1euHBhjI9MP26qLb2oBtSWHQWkStbFHzy1XFfilWG2Afd3hjEN+QAkvKT66Y1WlqQs5jTyWS8UBkVn4H8+wuxbnFtW3ZQzZy9+EW3e//5kKPPywNILSQ2c=
  matrix:
  - DESTINATION="OS=8.0,name=iPhone 4S"           SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"
  - DESTINATION="OS=9.0,name=iPhone 5"            SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"
  - DESTINATION="OS=10.0,name=iPhone 5S"          SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"
  - DESTINATION="OS=11.0,name=iPhone 6"           SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"
  - DESTINATION="OS=11.1,name=iPhone 6 Plus"      SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"
  - DESTINATION="OS=11.2,name=iPhone 6S"          SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"
  - DESTINATION="OS=11.2,name=iPhone 6S Plus"     SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"
  - DESTINATION="arch=x86_64"                     SCHEME="$OSX_FRAMEWORK_SCHEME"     SDK="$OSX_SDK"     RUN_TESTS="YES"
  - DESTINATION="OS=11.2,name=Apple TV 1080p"     SCHEME="$TVOS_FRAMEWORK_SCHEME"    SDK="$TVOS_SDK"    RUN_TESTS="YES"
  - DESTINATION="OS=4.2,name=Apple Watch - 38mm"  SCHEME="$WATCHOS_FRAMEWORK_SCHEME" SDK="$WATCHOS_SDK" RUN_TESTS="NO"
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c;
    else
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi

before_install:
- composer config --global github-oauth.github.com "$GITHUB_TOKEN"
- brew outdated carthage || brew upgrade carthage
- brew outdated swiftlint || brew upgrade swiftlint
before_script:
- carthage bootstrap
